#!/bin/bash
gcloud projects create ${artifactId}-${projectSuffix}

gcloud config set project ${artifactId}-${projectSuffix}

gcloud config set run/region us-central1

gcloud beta billing accounts list

echo "> Enter the billing account ID you want to use:"

read ACCOUNT_ID

gcloud beta billing projects link ${artifactId}-${projectSuffix} --billing-account=$ACCOUNT_ID

gcloud services enable cloudbuild.googleapis.com

gcloud services enable run.googleapis.com

PROJECT_NUMBER=`gcloud beta projects describe ${artifactId}-${projectSuffix} | grep 'projectNumber: ' | cut -d\   -f2 | tr -d \'`

gcloud projects add-iam-policy-binding ${artifactId}-${projectSuffix} --member serviceAccount:$PROJECT_NUMBER@cloudbuild.gserviceaccount.com --role roles/run.admin

gcloud projects add-iam-policy-binding ${artifactId}-${projectSuffix} --member serviceAccount:$PROJECT_NUMBER@cloudbuild.gserviceaccount.com --role roles/iam.serviceAccountUser

gcloud builds submit --config cloudbuild.yaml .
